apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  annotations:
  name: {{ .Release.Name }} 
  namespace: default
spec:
  maxReplicas: 10
  minReplicas: {{ .Values.replicas }}
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: {{ .Release.Name }}
  targetCPUUtilizationPercentage: 80
