apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: default
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
    spec:
      restartPolicy: Always
      containers:
      - image: {{ .Values.image.image_name }}:{{ .Values.image.image_tag}}
        imagePullPolicy: Always
        name: {{ .Release.Name }}
        envFrom:
        - secretRef:
            name: {{ .Release.Name }}
      nodeSelector:
        cloud.google.com/gke-nodepool: {{ .Values.default_pool_name }}
